### ISSUE TITLE
Need help resolving postgreSQL and deploying on Heroku

### ISSUE THREAD

**Issue by robertkng** [robertkng/project4#2]
Tried deploying to Heroku, no luck and I broke my postgreSQL. Got the below errors. 

$ psql postgres
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Tried these steps:

## Postgres Updating
https://keita.blog/2016/01/09/homebrew-and-postgresql-9-5/
#### My version of this lovely blog
brew services stop postgresql
brew update && brew upgrade postgresql
initdb /usr/local/var/postgres9.6.1 -E utf8
pg_upgrade \
  -d /usr/local/var/postgres \
  -D /usr/local/var/postgres9.6.1 \
  -b /usr/local/Cellar/postgresql/9.5.4/bin/ \
  -B /usr/local/Cellar/postgresql/9.6.1/bin/ \
  -v
mv /usr/local/var/postgres /usr/local/var/postgres9.5.4
mv /usr/local/var/postgres9.6.1 /usr/local/var/postgres
brew services start postgresql
gem uninstall p

Janelle told me Irwin was able to resolve this for her.

**Comment by robertkng** [comment]
@gittheking, @jasonseminara, @rapala61, @trevorpreston, @irwintsay @mgershowitz

**Comment by rapala61** [comment]
Hey rob, can you close this issue? thanks!
